[package]
name = "tgbot-worker-rs"
version = "0.1.0"
edition = "2021"
authors = ["xiaolin <446304319@qq.com>"]

[package.metadata.release]
release = false

# https://github.com/rustwasm/wasm-pack/issues/1247
[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.90"
console_error_panic_hook = { version = "0.1.7" }
convert_case = "0.6.0"
frankenstein = { git = "https://github.com/xlfish233/frankenstein", branch = "wasm-sup", features = ["async-http-client-wasm"], default-features = false }
paste = "1.0.15"
serde = "1.0.210"
serde_json = "1.0.131"  # Added serde_json dependency
worker = { version = "0.4.2", features = ["http", "axum"] }
axum = {version =  "0.7" ,default-features = false,features = ["json","macros"]}
tower-service = "0.3"
worker-macros = { version = "0.4.2" }
wasm-bindgen-futures = "0.4"
tracing = "0.1.40"
axum-wasm-macros = "0.1.2"
